=== cibuddy/cibuddy/main/project.configuration/src/main/resources/configuration-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:conf="http://com.cibuddy.project.configuration/schema/setup/v1-0"
           targetNamespace="http://com.cibuddy.project.configuration/schema/setup/v1-0" 
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- the root of all XML evil -->
    <xs:element name="setup">
        <xs:annotation>
            <xs:documentation>
                <xs:description>Root element to configure your build indicators.</xs:description>
                <xs:LineNumber>Root Element</xs:LineNumber>
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            <xs:description>An alias identifying this particular configuration. Should be unique, but is not enforced.</xs:description>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="configuration" type="conf:BuildTestConfigurationType" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            <xs:description>The actual configuration that combines all the configuration elements used above.</xs:description>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- the actual meat - what we want to test for -->
    <xs:complexType name="BuildTestConfigurationType">
        <xs:sequence>
            <xs:element name="projects" type="conf:ProjectsType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="trigger" type="conf:TriggerType" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="alias" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="ProjectsType">
        <xs:sequence>
            <xs:element name="project" type="conf:ProjectType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ProjectType">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:sequence>
                    <xs:element name="serverAlias" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="serverSource" type="xs:string" minOccurs="0" maxOccurs="1"/>
                </xs:sequence>
                <xs:element name="projectURL" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="TriggerType">
        <xs:sequence>
            <xs:element name="statusIndicator" type="conf:SimpleStatusIndicatorType" minOccurs="1" maxOccurs="1" />
            <xs:element name="action" type="conf:ActionIndicatorType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="SimpleStatusIndicatorType">
        <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:sequence>
                    <xs:element name="componendId" type="xs:string" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="indicatorId" type="xs:string" minOccurs="1" maxOccurs="1"/>
                </xs:sequence>
                <xs:element name="id" type="xs:integer" minOccurs="1" maxOccurs="1"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ActionIndicatorType">
        <xs:sequence>
            <xs:element name="status" minOccurs="0" maxOccurs="15">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="red"/>
                        <xs:enumeration value="red_anime"/>
                        <xs:enumeration value="yellow"/>
                        <xs:enumeration value="yellow_anime"/>
                        <xs:enumeration value="blue"/>
                        <xs:enumeration value="blue_anime"/>
                        <xs:enumeration value="grey"/>
                        <xs:enumeration value="grey_anime"/>
                        <xs:enumeration value="disabled"/>
                        <xs:enumeration value="disabled_anime"/>
                        <xs:enumeration value="aborted"/>
                        <xs:enumeration value="aborted_anime"/>
                        <xs:enumeration value="notbuilt"/>
                        <xs:enumeration value="notbuilt_anime"/>
                        <xs:enumeration value="default"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="indicate" minOccurs="1" maxOccurs="1" default="off">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="success"/>
                        <xs:enumeration value="warning"/>
                        <xs:enumeration value="failure"/>
                        <xs:enumeration value="building"/>
                        <xs:enumeration value="off"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="condition" default="all">
            <xs:annotation>
                <xs:documentation>
                    <xs:description>
                        A condition specifies what exactly has to be true. Does
                        all builds have to match the indicators or just one or
                        just a percentage? The syntax is like that:
                        - "all": every project in this configuration has to match at least one of the stati.
                        - "n:*": n as int, that represents the (minimum) number of matching projects.
                        - "n:m": n,m as int, that represent a fraction that should at least match.
                        - "default": catch all. After this the processing always stops and activates the given indicator
                    </xs:description>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== cibuddy/cibuddy/main/project.configuration/src/test/resources/sample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<setup  xmlns="http://net.mjahn.jenkins/schema/configruation/v1-0" 
		xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation='http://net.mjahn.jenkins/schema/configruation/v1-0 ../../main/resources/configuration-1.0.xsd'>

    <name>test</name>
    <configuration alias="config1">
        <projectTriggers>
            <project>
                <name>cibuddy</name>
                <projectURL>http://localhost:8080/job/cibuddy%20masterbuild/</projectURL>
            </project>
            <trigger>
                <status>SUCCESS</status>
            </trigger>
        </projectTriggers>
        <statusIndicators>
            <statusIndicator>
                <id>0</id>
            </statusIndicator>
        </statusIndicators>
    </configuration>
</setup>

=== cibuddy/cibuddy/distributions/pax.assembly/src/main/resources/deploy/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<setup  xmlns="http://net.mjahn.jenkins/schema/configruation/v1-0" 
		xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation='http://net.mjahn.jenkins/schema/configruation/v1-0 ../../main/resources/configuration-1.0.xsd'>

    <name>test</name>
    <configuration alias="defaultConfig">
        <projects>
            <project>
                <name>cibuddy</name>
                <projectURL>http://localhost:8080/job/cibuddy%20masterbuild/</projectURL>
            </project>
        </projects>
        <trigger>
            <statusIndicator>
                <id>0</id>
            </statusIndicator>
            <action status="blue" condition="all">
                <indicate>success</indicate>
            </action>
            <action status="red" condition="1:*"><!-- at least one -->
                <indicate>failure</indicate>
            </action>
            <action status="yellow" condition="1:*"><!-- at least one -->
                <indicate>warning</indicate>
            </action>
            <action status="default"><!-- at least one -->
                <indicate>off</indicate>
            </action>
        </trigger>
    </configuration>
</setup>
