=== cibuddy/cibuddy/main/project.configuration/src/main/resources/indicator-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:this="http://com.cibuddy.project.configuration/schema/behavior/v1-0"
           targetNamespace="http://com.cibuddy.project.configuration/schema/behavior/v1-0"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0" 
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:annotation>
        <xs:appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="com.cibuddy.project.configuration.jaxb.v1_0.indicator"/>
            </jaxb:schemaBindings>
        </xs:appinfo>
    </xs:annotation>

    <!-- the root of all XML evil -->
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="action" type="this:ColorIndicatorType" minOccurs="1" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            <xs:description>An alias identifying this particular configuration. Should be unique, but is not enforced.</xs:description>
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="ColorIndicatorType">
        <xs:annotation>
            <xs:appinfo>
                <jaxb:class name="ColorIndicator"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="status" minOccurs="0" maxOccurs="15">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <!-- Jenkins and Hudson values -->
                        <xs:enumeration value="red"/>
                        <xs:enumeration value="red_anime"/>
                        <xs:enumeration value="yellow"/>
                        <xs:enumeration value="yellow_anime"/>
                        <xs:enumeration value="blue"/>
                        <xs:enumeration value="blue_anime"/>
                        <xs:enumeration value="grey"/>
                        <xs:enumeration value="grey_anime"/>
                        <xs:enumeration value="disabled"/>
                        <xs:enumeration value="disabled_anime"/>
                        <xs:enumeration value="aborted"/>
                        <xs:enumeration value="aborted_anime"/>
                        <xs:enumeration value="notbuilt"/>
                        <xs:enumeration value="notbuilt_anime"/>
                        <!-- Travis-CI established values -->
                        <xs:enumeration value="0"/> <!-- success -->
                        <xs:enumeration value="1"/> <!-- failure -->
                        
                        <!-- special status for "catch all" -->
                        <xs:enumeration value="default"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="indicate" minOccurs="1" maxOccurs="1" default="off">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="success"/>
                        <xs:enumeration value="warning"/>
                        <xs:enumeration value="failure"/>
                        <xs:enumeration value="building"/>
                        <xs:enumeration value="off"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="condition" default="all">
            <xs:annotation>
                <xs:documentation>
                    <xs:description>
                        A condition specifies what exactly has to be true. Does
                        all builds have to match the indicators or just one or
                        just a percentage? The syntax is like that:
                        - "all": every project in this configuration has to match at least one of the stati.
                        - "n:*": n as int, that represents the (minimum) number of matching projects.
                        - "n:m": n,m as int, that represent a fraction that should at least match.
                        - "default": catch all. After this the processing always stops and activates the given indicator
                    </xs:description>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== cibuddy/cibuddy/main/project.configuration/src/test/resources/indicator-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2012 Mirko Jahn <mirkojahn@gmail.com>

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<config  xmlns="http://com.cibuddy.project.configuration/schema/behavior/v1-0" 
         xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation='http://com.cibuddy.project.configuration/schema/behavior/v1-0 ../../main/resources/indicator-1.0.xsd'
         name="default">
    <action condition="all">
        <status>blue</status>
        <status>blue_anime</status>
        <indicate>success</indicate>
    </action>
    <action condition="1:*"><!-- at least one -->
        <status>red</status>
        <status>red_anime</status>
        <indicate>failure</indicate>
    </action>
    <action condition="1:*"><!-- at least one -->
        <status>yellow</status>
        <status>yellow_anime</status>
        <indicate>warning</indicate>
    </action>
    <action condition="default"><!-- catch all -->
        <indicate>off</indicate>
    </action>
</config>
